version: "3.8"

services:
  client:
    image: client-dev-i
    build:
      context: 
        ./client
      dockerfile: Dockerfile.dev
    container_name: client-dev-c
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  
  strapi:
    build:
      context: 
        ./cms
      dockerfile: Dockerfile.dev
    container_name: hirctf-strapi-dev-c
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=development

    

volumes:
  node_modules: