version: "3.8"
services:
  client:
    build:
      dockerfile: Dockerfile.prod
    container_name: client-prod-c
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
  strapi:
    build:
      context: ./cms
      dockerfile: Dockerfile.prod
    container_name: hirctf-strapi-prod-c
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
