export const images = {
    about: require('./OBJECTS.svg'),
    consultancy_service: require('./home_bannerb.jpg'),
    research_service: require('./research.jpg'),
    training_service: require('./traning.jpg'),
    project: require('./project.svg'),
    fileicon: require('./fileicon.png'),
    test1: require('./testi.jpg'),
    test2: require('./testi2.jpg'),
    gallery1: require('./gallery1.jpg'),
    gallery2: require('./gallery2.jpg'),
    gallery3: require('./gallery3.jpg'),
    gallery4: require('./gallery4.jpg'),
    blog1: require('./blog1.jpeg'),
    blog2: require('./blog2.jpg'),
    avatar: require('./User-avatar 1.png'),
    consulting: require('./banner-consulting-concept-text-icons-260nw-770977666 1.png'),
    hero: require('./hero.svg'),
    intro: require('./intro.png'),
    offer: require('./offer.png'),
    offermobil: require('./offermobile.png'),
    logo1: require('./logo1.png'),
    logo2: require('./logo2.png')
}