name: Deploy to VPS

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install

      - name: Build React App
        run: |
          npm run build
      
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
            scp -r ./build/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/horn/
            
    