name: Deploy to VPS

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/HIRCTF/
          git pull origin main
          git status
          npm install --only=prod