name: CI/CD for React App

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 82.180.131.73 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh root@82.180.131.73 "cd /path/to/app && git pull && docker-compose up -d"
