name: Deploy to VPS

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
        - uses: actions/checkout@v1
        - run: npm install
        - run: npm run build