name: Deploy to VPS

on:
  push:
    branches:
      - master # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install

      - name: Build React App
        run: |
          npm run build

      - name: Debug - List files in workspace
        run: |
          ls -R
          echo "Current directory: $(pwd)"
        working-directory: ./build

      - name: Deploy to VPS
        run: |
          scp -r ./build/* root@82.180.131.73:/var/www/my-react-app/
